version: 1

app:
  env: dev
  mode: release # Mode is either debug or release
  port: 8080
  forwarderType: pubsub

routing:
  includeStandardRoutes: true
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r

cookie:
  name: sp-nuid
  secure: False
  ttlDays: 365
  domain: localhost
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

pubsub:
  project: "dev-sixrs-data-platform"
  validEventTopic: "test-valid-topic"
  invalidEventTopic: "test-invalid-topic"
  bufferByteThreshold: 1024
  bufferRecordThreshold: 100
  bufferDelayThreshold: 10000000000



# parser:
#   extractCookies: True

# telemetry:
#   enable: False
