version: 1

app:
  env: dev
  mode: debug # Mode is either debug or release
  port: 8080
  forwarderType: pubsub

routing:
  includeStandardRoutes: true
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r

cookie:
  name: sp-nuid
  secure: False
  ttlDays: 365
  domain: localhost
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

anonymize:
  ip: false
  user_id: false

registry:
  type: gcs # gcs, s3, abs, or local
  location: # either a remote url or local fs path

pubsub:
  project: "dev-sixrs-data-platform"
  validEventTopic: "test-valid-topic"
  invalidEventTopic: "test-invalid-topic"
  bufferByteThreshold: 1024
  bufferRecordThreshold: 100
  bufferDelayThreshold: 10000000000

tele:
  enable: true
