version: 1

app:
  env: dev
  mode: debug # Mode is either debug or release
  port: 8081
  forwarderType: pubsub

routing:
  includeStandardRoutes: true
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r

cookie:
  name: sp-nuid
  secure: False
  ttlDays: 365
  domain: localhost
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

anonymize:
  ip: false
  userId: false

cache:
  backend:
    type: gcs
    location: gosnowplow-schemas-test
    path: /
  ttlSeconds: 300
  maxSizeBytes: 104857600 # 100mb -> 100 * 1024 * 1024

pubsub:
  project: "bostata-internal"
  validEventTopic: "test-topic"
  invalidEventTopic: "test-topic"
  bufferByteThreshold: 1024
  bufferRecordThreshold: 100
  bufferDelayThreshold: 10000000000

tele:
  enable: true
