version: 1

app:
  env: dev
  mode: debug # Mode is either debug or release
  port: 8081

snowplow: # Snowplow Events
  enabled: true
  standardRoutesEnabled: true
  openRedirectsEnabled: true
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r

generic: # Generic Self-Describing Events
  enabled: true
  postPath: /gen/p
  batchPostPath: /gen/bp
  contextsKey: contexts
  payloadKey: payload

cookie:
  name: sp-nuid
  secure: False
  ttlDays: 365
  domain: $YOUR_DOMAIN
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

anonymize:
  ip: false
  userId: false

schemaCache:
  schemaCacheBackend:
    type: s3
    bucket: $SCHEMA_BUCKET
    path: /
  ttlSeconds: 300
  maxSizeBytes: 104857600 # 100mb -> 100 * 1024 * 1024

# ============================================================
# Example schema cache with GCS backend
# schemaCache:
#   schemaCacheBackend:
#     type: s3
#     bucket: $SCHEMA_BUCKET
#     path: /
#   ttlSeconds: 300
#   maxSizeBytes: 104857600 # 100mb -> 100 * 1024 * 1024
# ============================================================

forwarder:
  type: kafka
  brokers:
    - $KAFKA_BROKER_1:9092
    - $KAFKA_BROKER_2:9092
    - $KAFKA_BROKER_3:9092
  validEventTopic: $YOUR_VALID_EVENT_TOPIC
  invalidEventTopic: $YOUR_INVALID_EVENT_TOPIC

# ============================================================
# Example pubsub forwarder config
# forwarder:
#   type: pubsub
#   project: YOUR_PROJECT_HERE
#   validEventTopic: YOUR_VALID_EVENT_TOPIC_HERE
#   invalidEventTopic: YOUR_INVALID_EVENT_TOPIC_HERE
# ============================================================
