version: 1

app:
  env: dev
  mode: release # Mode is either debug or release
  port: 8081

routing:
  disableStandardRoutes: false
  disableOpenRedirect: true # Probably want to turn this off in production if unused. 
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r

cookie:
  name: sp-nuid
  secure: False
  ttlDays: 365
  domain: localhost
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

anonymize:
  ip: false
  userId: false

cache:
  backend:
    type: gcs
    location: gosnowplow-schemas-test
    # location: watershed-schemas-test
    path: /
  ttlSeconds: 300
  maxSizeBytes: 104857600 # 100mb -> 100 * 1024 * 1024

forwarder:
  type: pubsub
  # project: "bostata-internal"
  project: dev-sixrs-data-platform
  validEventTopic: test-valid-topic
  invalidEventTopic: test-invalid-topic
  bufferByteThreshold: 1024
  bufferRecordThreshold: 100
  bufferDelayThreshold: 10000000000

tele:
  enable: true
