version: 1

app:
  env: development
  mode: release
  port: 8081
  trackerDomain: demo.example.io
  stats:
    enabled: true
    path: /stats
  timeout:
    enabled: true
    ms: 5000
  rateLimiter:
    enabled: false
    period: S
    limit: 15

snowplow:
  enabled: true
  standardRoutesEnabled: true
  openRedirectsEnabled: false
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r
  anonymize:
    ip: true
    userId: true

cloudevents:
  enabled: true
  postPath: /ce/p
  batchPostPath: /ce/bp

generic:
  enabled: true
  postPath: /gen/p
  batchPostPath: /gen/bp
  contexts:
    rootKey: contexts
    schemaKey: schema
    dataKey: payload
  payload:
    rootKey: payload
    schemaKey: schema
    dataKey: payload

cookie:
  enabled: true
  name: sp-nuid
  secure: true
  ttlDays: 365
  domain: example.io
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

schemaCache:
  schemaCacheBackend:
    type: fs
    path: /schemas
  ttlSeconds: 300
  maxSizeBytes: 104857600 # 100mb -> 100 * 1024 * 1024
  purge:
    enabled: false
    path: /c/purge
  schemaEndpoints:
    enabled: true

sink:
  type: kafka
  brokers:
    - BROKER1:9092
    - BROKER2:9092
    - BROKER3:9092
  validEventTopic: test-valid-topic
  invalidEventTopic: test-invalid-topic
  produceTimeout: 5

tele:
  enabled: true
  heartbeatMs: 30000
