version: "3.9"

services:
  honeypot:
    container_name: honeypot
    image: ghcr.io/silverton-io/honeypot:v0.1.43
    volumes:
      - type: bind
        source: ./honeypot/elastic-kibana.conf.yml
        target: /etc/honeypot/config.yml
      - type: bind
        source: ../../schemas
        target: /schemas/
      - type: bind
        source: ../../site/index.html
        target: /app/site/index.html
    environment:
      - HONEYPOT_CONFIG_PATH=/etc/honeypot/config.yml
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl -f localhost:8080/health
      interval: 15s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: elasticsearch
    environment:
      - cluster.name=honeypot-cluster
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  kibana:
      image: docker.elastic.co/kibana/kibana:8.1.0
      container_name: kibana
      environment:
        - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      ports:
        - "5601:5601"
      depends_on:
        elasticsearch:
          condition: service_healthy

volumes:
  esdata1:
    driver: local
