name: Releaser

on:
  push:
    branches:
      - main

jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cut Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true

  publish-go-binaries:
    runs-on: ubuntu-latest
    needs: cut-release
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Version from file
        id: get-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.VERSION

      - name: Release Binaries
        uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: make
          release_tag: ${{ steps.get-version.outputs.content }}
          binary_name: honeypot
          extra_files: LICENSE .VERSION
