version: "3.9"

services:
  honeypot:
    container_name: honeypot
    image: ghcr.io/silverton-io/honeypot:v0.1.44
    volumes:
      - type: bind
        source: ./honeypot/quickstart.conf.yml
        target: /etc/honeypot/config.yml
      - type: bind
        source: ../../schemas
        target: /schemas/
      - type: bind
        source: ../../site/index.html
        target: /app/site/index.html
    environment:
      - HONEYPOT_CONFIG_PATH=/etc/honeypot/config.yml
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl -f localhost:8080/health
      interval: 15s
    depends_on:
      redpanda-init:
        condition: service_completed_successfully

  redpanda-1:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.9 # Note! Use the latest version :)
    container_name: redpanda-1
    command:
      - redpanda start
      - --overprovisioned
      - --check=false
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --kafka-addr
      - INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - INSIDE://redpanda-1:29092,OUTSIDE://127.0.0.1:9092
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda-1:33145
      - --set redpanda.enable_transactions=true
      - --set redpanda.enable_idempotence=true
    ports:
      - 9092:9092
    healthcheck:
      test: curl -f localhost:9644/v1/status/ready
      interval: 1s
      start_period: 30s

  redpanda-2:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.9 # Note! Use the latest version :)
    container_name: redpanda-2
    command:
      - redpanda start
      - --overprovisioned
      - --check=false
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 1
      - --seeds "redpanda-1:33145"
      - --kafka-addr
      - INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - INSIDE://redpanda-2:29093,OUTSIDE://127.0.0.1:9093
      - --rpc-addr 0.0.0.0:33146
      - --advertise-rpc-addr redpanda-2:33146
      - --set redpanda.enable_transactions=true
      - --set redpanda.enable_idempotence=true
    ports:
      - 9093:9093
    healthcheck:
      test: curl -f localhost:9644/v1/status/ready
      interval: 1s
      start_period: 30s

  redpanda-3:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.9 # Note! Use the latest version :)
    container_name: redpanda-3
    command:
      - redpanda start
      - --overprovisioned
      - --check=false
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 2
      - --seeds "redpanda-1:33145"
      - --kafka-addr
      - INSIDE://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
      - --advertise-kafka-addr
      - INSIDE://redpanda-3:29094,OUTSIDE://127.0.0.1:9094
      - --rpc-addr 0.0.0.0:33147
      - --advertise-rpc-addr redpanda-3:33147
      - --set redpanda.enable_transactions=true
      - --set redpanda.enable_idempotence=true
    ports:
      - 9094:9094
    healthcheck:
      test: curl -f localhost:9644/v1/status/ready
      interval: 1s
      start_period: 30s

  redpanda-init:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.9 # Note! Use the latest version :)
    container_name: redpanda-init
    command:
      - cluster metadata --brokers redpanda-1:29092,redpanda-2:29093,redpanda-3:29094
    depends_on:
      redpanda-1:
        condition: service_healthy
      redpanda-2:
        condition: service_healthy
      redpanda-3:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  materialized:
    container_name: materialized
    image: materialize/materialized # Note! Use the latest version :)
    init: true
    command: -w2 --disable-telemetry
    ports:
      - 6875:6875

  kowl:
    image: quay.io/cloudhut/kowl:v1.5.0
    restart: on-failure
    container_name: kowl
    volumes:
    - ./kowl/quickstart.yml:/etc/kowl/config.yml
    ports:
    - "8081:8081"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yml
    depends_on:
      redpanda-1:
        condition: service_healthy
      redpanda-2:
        condition: service_healthy
      redpanda-3:
        condition: service_healthy

  mzcli:
    container_name: mzcli
    image: materialize/cli
