version: "3.9"

x-app:
  &redpanda
  image: docker.vectorized.io/vectorized/redpanda:latest # Note! Use the latest version :)
  healthcheck:
    test: curl -f localhost:9644/v1/status/ready
    interval: 1s
    start_period: 30s

x-dependency:
  &redpanda-dep
  redpanda-1:
    condition: service_healthy
  redpanda-2:
    condition: service_healthy
  redpanda-3:
    condition: service_healthy

services:
  buz:
    container_name: buz
    image: ghcr.io/silverton-io/buz:v0.15.3
    volumes:
      - type: bind
        source: ./buz/quickstart.conf.yml
        target: /etc/buz/config.yml
      - type: bind
        source: ../../schemas
        target: /schemas/
    environment:
      - BUZ_CONFIG_PATH=/etc/buz/config.yml
      - DEBUG=1
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ./healthcheck --host=localhost --port=8080 --path=/health
      interval: 1s
    depends_on:
      << : *redpanda-dep

  buz-quickstart-ui:
    container_name: buz-quickstart-ui
    image: ghcr.io/silverton-io/sample-tracked-ui:0.1.5

  buz-quickstart-proxy:
    container_name: buz-quickstart-proxy
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 8081:8081
    depends_on:
      buz:
        condition: service_healthy

  redpanda-1:
    << : *redpanda
    container_name: redpanda-1
    command:
      - redpanda start
      - --overprovisioned
      - --check=false
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --kafka-addr
      - INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - INSIDE://redpanda-1:29092,OUTSIDE://127.0.0.1:9092
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda-1:33145
      - --set redpanda.enable_transactions=true
      - --set redpanda.enable_idempotence=true
    ports:
      - 9092:9092

  redpanda-2:
    << : *redpanda
    container_name: redpanda-2
    command:
      - redpanda start
      - --overprovisioned
      - --check=false
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 1
      - --seeds "redpanda-1:33145"
      - --kafka-addr
      - INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - INSIDE://redpanda-2:29093,OUTSIDE://127.0.0.1:9093
      - --rpc-addr 0.0.0.0:33146
      - --advertise-rpc-addr redpanda-2:33146
      - --set redpanda.enable_transactions=true
      - --set redpanda.enable_idempotence=true
    ports:
      - 9093:9093

  redpanda-3:
    << : *redpanda
    container_name: redpanda-3
    command:
      - redpanda start
      - --overprovisioned
      - --check=false
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 2
      - --seeds "redpanda-1:33145"
      - --kafka-addr
      - INSIDE://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
      - --advertise-kafka-addr
      - INSIDE://redpanda-3:29094,OUTSIDE://127.0.0.1:9094
      - --rpc-addr 0.0.0.0:33147
      - --advertise-rpc-addr redpanda-3:33147
      - --set redpanda.enable_transactions=true
      - --set redpanda.enable_idempotence=true
    ports:
      - 9094:9094

  console:
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    container_name: console
    environment:
      - KAFKA_BROKERS=redpanda-1:29092,redpanda-2:29093,redpanda-3:29094
    ports:
    - 8082:8080
    depends_on:
      << : *redpanda-dep
